Restore build for systems like Tru64 where ld does not acccept -R

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -2983,7 +2983,65 @@ CFLAGS=$SAVEDCFLAGS
 
 NORPSAVEDLDFLAGS=$LDFLAGS
 
-# Check if the linker accepts --rpath (for Darwin)
+# Any linker will probably accept -L
+rpath="-L"
+
+# Check if the linker accepts -R
+echo "$as_me:$LINENO: checking if ld accepts -Rh" >&5
+echo $ECHO_N "checking if ld accepts -Rh... $ECHO_C" >&6
+SAVEDLDFLAGS=$LDFLAGS
+LDFLAGS=$LDFLAGS" -Wl,-R=/"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  rpath="-R"; ldrpath=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ldrpath=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LDFLAGS=$SAVEDLDFLAGS
+echo "$as_me:$LINENO: result: $ldrpath" >&5
+echo "${ECHO_T}$ldrpath" >&6
+
+# Check if the linker accepts --rpath
 echo "$as_me:$LINENO: checking if ld accepts --rpath" >&5
 echo $ECHO_N "checking if ld accepts --rpath... $ECHO_C" >&6
 SAVEDLDFLAGS=$LDFLAGS
@@ -3030,7 +3088,7 @@ else
   echo "$as_me: failed program was:" >&5
 sed 's/^/| /' conftest.$ac_ext >&5
 
-rpath="-R"; ldrpath=no
+ldrpath=no
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
