Regen for newer libspf2

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -848,6 +848,7 @@ Optional Packages:
   --with-libmilter=DIR   Find libmilter in DIR
   --with-libpthread=DIR  Find libpthread in DIR
   --with-libspf2=DIR  Find libspf2 in DIR
+  --with-libspf2_10=DIR  Find libspf2 1.0 in DIR
   --with-libspf_alt=DIR  Find libspf_alt in DIR
   --with-libspf=DIR  Find libspf in DIR
   --with-user=USERNAME   The user that will run milter-greylist
@@ -5328,6 +5329,180 @@ if test "${with_libspf2+set}" = set; then
   withval="$with_libspf2"
   LDFLAGS=$LDFLAGS" -L$withval/lib -Wl,$rpath$withval/lib"
            CFLAGS=$CFLAGS" -I$withval/include"
+           echo "$as_me:$LINENO: checking for SPF_server_new in -lspf2" >&5
+echo $ECHO_N "checking for SPF_server_new in -lspf2... $ECHO_C" >&6
+if test "${ac_cv_lib_spf2_SPF_server_new+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lspf2  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SPF_server_new ();
+int
+main ()
+{
+SPF_server_new ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_spf2_SPF_server_new=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_spf2_SPF_server_new=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_spf2_SPF_server_new" >&5
+echo "${ECHO_T}$ac_cv_lib_spf2_SPF_server_new" >&6
+if test $ac_cv_lib_spf2_SPF_server_new = yes; then
+
+               SAVEDLDFLAGS=$LDFLAGS
+               SAVEDCFLAGS=$CFLAGS
+               LIBS=$LIBS"-lspf2"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SPF2
+_ACEOF
+
+
+else
+  echo "$as_me:$LINENO: checking for SPF_server_new in -lspf2 -lintl" >&5
+echo $ECHO_N "checking for SPF_server_new in -lspf2 -lintl... $ECHO_C" >&6
+if test "${ac_cv_lib_spf2__lintl_SPF_server_new+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lspf2 -lintl  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any gcc2 internal prototype to avoid an error.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+/* We use char because int might match the return type of a gcc2
+   builtin and then its argument prototype would still apply.  */
+char SPF_server_new ();
+int
+main ()
+{
+SPF_server_new ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_lib_spf2__lintl_SPF_server_new=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+ac_cv_lib_spf2__lintl_SPF_server_new=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_lib_spf2__lintl_SPF_server_new" >&5
+echo "${ECHO_T}$ac_cv_lib_spf2__lintl_SPF_server_new" >&6
+if test $ac_cv_lib_spf2__lintl_SPF_server_new = yes; then
+
+                       SAVEDLDFLAGS=$LDFLAGS
+                       SAVEDCFLAGS=$CFLAGS
+                       LIBS=$LIBS"-lspf2 -lintl"
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_SPF2
+_ACEOF
+
+
+else
+  echo "libspf2 not found, check config.log for details"
+                   echo "Remove --with-libspf2 to build without SPF support"
+                   exit 1;
+fi
+
+
+fi
+
+
+fi;
+LDFLAGS=$SAVEDLDFLAGS
+CFLAGS=$SAVEDCFLAGS
+
+# Try to configure for libspf2 1.0
+SAVEDLDFLAGS=$LDFLAGS
+SAVEDCFLAGS=$CFLAGS
+
+# Check whether --with-libspf2_10 or --without-libspf2_10 was given.
+if test "${with_libspf2_10+set}" = set; then
+  withval="$with_libspf2_10"
+  LDFLAGS=$LDFLAGS" -L$withval/lib -Wl,$rpath$withval/lib"
+           CFLAGS=$CFLAGS" -I$withval/include"
            echo "$as_me:$LINENO: checking for SPF_create_config in -lspf2" >&5
 echo $ECHO_N "checking for SPF_create_config in -lspf2... $ECHO_C" >&6
 if test "${ac_cv_lib_spf2_SPF_create_config+set}" = set; then
@@ -5399,7 +5574,7 @@ if test $ac_cv_lib_spf2_SPF_create_config = yes; then
                LIBS=$LIBS"-lspf2"
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_SPF2
+#define HAVE_SPF2_10
 _ACEOF
 
 
@@ -5475,13 +5650,13 @@ if test $ac_cv_lib_spf2__lintl_SPF_create_config = yes; then
                        LIBS=$LIBS"-lspf2 -lintl"
 
 cat >>confdefs.h <<\_ACEOF
-#define HAVE_SPF2
+#define HAVE_SPF2_10
 _ACEOF
 
 
 else
-  echo "libspf2 not found, check config.log for details"
-                   echo "Remove --with-libspf2 to build without SPF support"
+  echo "libspf2 1.0 not found, check config.log for details"
+                   echo "Remove --with-libspf2_10 to build without SPF support"
                    exit 1;
 fi
 
