Check for -D_SGI_SOURCE on IRIX

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -8014,7 +8014,68 @@ rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
 echo "$as_me:$LINENO: result: $xopen" >&5
 echo "${ECHO_T}$xopen" >&6
 
-# IRIX requires -D_XOPEN_SOURCE=500 to use <stdio.h> and -ansi
+# IRIX requires -D_SGI_SOURCE to use <stdio.h> and -ansi
+echo "$as_me:$LINENO: checking whether you need -D_SGI_SOURCE to use <stdio.h> with -ansi" >&5
+echo $ECHO_N "checking whether you need -D_SGI_SOURCE to use <stdio.h> with -ansi... $ECHO_C" >&6
+SAVEDCFLAGS=$CFLAGS
+CFLAGS=$CFLAGS" -ansi"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+		#include <stdio.h>
+
+int
+main ()
+{
+
+		FILE *f;
+
+		f = fdopen(0, "w+");
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  xstdio=no
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+SAVEDCFLAGS=$SAVEDCFLAGS" -D_SGI_SOURCE";
+	 xstdio=yes
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+CFLAGS=$SAVEDCFLAGS
+echo "$as_me:$LINENO: result: $xstdio" >&5
+echo "${ECHO_T}$xstdio" >&6
+
+# IRIX may also require -D_XOPEN_SOURCE=500 to use <stdio.h> and -ansi
 echo "$as_me:$LINENO: checking whether you need -D_XOPEN_SOURCE to use <stdio.h> with -ansi" >&5
 echo $ECHO_N "checking whether you need -D_XOPEN_SOURCE to use <stdio.h> with -ansi... $ECHO_C" >&6
 SAVEDCFLAGS=$CFLAGS
